/*
 * Copyright (C) 2012 Freescale Semiconductor, Inc.
 *
 * Author: Fabio Estevam <fabio.estevam@freescale.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#include <asm/arch/clock.h>
#include <asm/arch/imx-regs.h>
#include <asm/arch/iomux.h>
#include <asm/arch/mx6-pins.h>
#include <linux/errno.h>
#include <asm/imx-common/iomux-v3.h>

static iomux_v3_cfg_t const iomux_v3_pads[] = {

	/* Watch dog */
	IOMUX_PADS(PAD_GPIO_1__WDOG2_B            | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* WDOG_B to reset pmic */
	
	/* LVDS */
	IOMUX_PADS(PAD_SD1_DAT1__GPIO1_IO17       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LVDS_BLEN */
	IOMUX_PADS(PAD_GPIO_2__GPIO1_IO02         | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LCD_BLK_3.3V */
	IOMUX_PADS(PAD_GPIO_9__GPIO1_IO09         | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LCD_BLK_5V */
	IOMUX_PADS(PAD_NANDF_D3__GPIO2_IO03       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LCD_12V_EN */
	IOMUX_PADS(PAD_GPIO_7__GPIO1_IO07         | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LCD_12_24V_EN */
	IOMUX_PADS(PAD_EIM_D23__GPIO3_IO23        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* ADJ_PNL */
	IOMUX_PADS(PAD_SD1_CMD__PWM4_OUT          | MUX_PAD_CTRL(0x1b0b1)),		/* LVDS PWM4 */

	/* LCD */
	IOMUX_PADS(PAD_GPIO_19__GPIO4_IO05        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LCD_EDID_EN */	
	IOMUX_PADS(PAD_GPIO_4__GPIO1_IO04         | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* VGA DAC ENABLE */

	/* GPIO */
	IOMUX_PADS(PAD_ENET_TX_EN__GPIO1_IO28     | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO1 */
	IOMUX_PADS(PAD_ENET_RXD0__GPIO1_IO27      | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO2 */
	IOMUX_PADS(PAD_ENET_TXD0__GPIO1_IO30      | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO3 */
	IOMUX_PADS(PAD_KEY_COL1__GPIO4_IO08       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO4 */
	IOMUX_PADS(PAD_KEY_ROW1__GPIO4_IO09       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO5 */
	IOMUX_PADS(PAD_EIM_D26__GPIO3_IO26        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO6 */
	IOMUX_PADS(PAD_EIM_D27__GPIO3_IO27        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO7 */
	IOMUX_PADS(PAD_EIM_D28__GPIO3_IO28        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO8 */
	IOMUX_PADS(PAD_EIM_D31__GPIO3_IO31        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* GPIO9 */
	
	/* Audio Codec */
	IOMUX_PADS(PAD_GPIO_0__CCM_CLKO1	      | MUX_PAD_CTRL(0x130b0)),		/* SGTL5000 sys_mclk */
	IOMUX_PADS(PAD_SD3_RST__GPIO7_IO08        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* HEADPHONE_DET */
	IOMUX_PADS(PAD_CSI0_DAT18__GPIO6_IO04     | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* HEADPHONE POP enable */
	IOMUX_PADS(PAD_NANDF_D6__GPIO2_IO06       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* AUD_AMP_STBY_B */
	IOMUX_PADS(PAD_NANDF_D7__GPIO2_IO07       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* AMP MUTE_B */
	
	/* IR */
	IOMUX_PADS(PAD_SD3_DAT5__GPIO7_IO00       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* IR_C */

	/* LED */
	IOMUX_PADS(PAD_SD3_DAT6__GPIO6_IO18       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LED_R_C */
	IOMUX_PADS(PAD_SD3_DAT7__GPIO6_IO17       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* LED_G_C */

	/* audmux */
	IOMUX_PADS(PAD_CSI0_DAT7__AUD3_RXD        | MUX_PAD_CTRL(0x130b0)),
	IOMUX_PADS(PAD_CSI0_DAT4__AUD3_TXC        | MUX_PAD_CTRL(0x130b0)),
	IOMUX_PADS(PAD_CSI0_DAT5__AUD3_TXD        | MUX_PAD_CTRL(0x110b0)),
	IOMUX_PADS(PAD_CSI0_DAT6__AUD3_TXFS       | MUX_PAD_CTRL(0x130b0)),

	/* enet */
	IOMUX_PADS(PAD_ENET_MDIO__ENET_MDIO	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_ENET_MDC__ENET_MDC	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TXC__RGMII_TXC	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TD0__RGMII_TD0	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TD1__RGMII_TD1	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TD2__RGMII_TD2	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TD3__RGMII_TD3	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_TX_CTL__RGMII_TX_CTL | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_ENET_REF_CLK__ENET_TX_CLK  | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RXC__RGMII_RXC	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RD0__RGMII_RD0	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RD1__RGMII_RD1	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RD2__RGMII_RD2	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RD3__RGMII_RD3	      | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_RGMII_RX_CTL__RGMII_RX_CTL | MUX_PAD_CTRL(0x1b0b0)),
	IOMUX_PADS(PAD_ENET_RXD1__GPIO1_IO26      | MUX_PAD_CTRL(0x000b1)),  /* RGMII_INT */
	IOMUX_PADS(PAD_ENET_CRS_DV__GPIO1_IO25    | MUX_PAD_CTRL(0x1b0b0)),  /* RGMII_nRST */

	/* hdmi */
	IOMUX_PADS(PAD_KEY_ROW2__HDMI_TX_CEC_LINE | MUX_PAD_CTRL(0x1f8b0)),  /* HDMI CEC */

	/* i2c1 */
	IOMUX_PADS(PAD_CSI0_DAT8__I2C1_SDA        | MUX_PAD_CTRL(0x1b8b1)),
	IOMUX_PADS(PAD_CSI0_DAT9__I2C1_SCL        | MUX_PAD_CTRL(0x1b8b1)),

	/* i2c2 */
	IOMUX_PADS(PAD_KEY_COL3__I2C2_SCL         | MUX_PAD_CTRL(0x1b8b1)),
	IOMUX_PADS(PAD_KEY_ROW3__I2C2_SDA         | MUX_PAD_CTRL(0x1b8b1)),

	/* i2c3 */
	IOMUX_PADS(PAD_GPIO_5__I2C3_SCL           | MUX_PAD_CTRL(0x1b8b1)),
	IOMUX_PADS(PAD_GPIO_6__I2C3_SDA           | MUX_PAD_CTRL(0x1b8b1)),
	
	/* ipu1 */
	IOMUX_PADS(PAD_DI0_DISP_CLK__IPU1_DI0_DISP_CLK | MUX_PAD_CTRL(0x10)),   /* DISP0 CLK */
	IOMUX_PADS(PAD_DI0_PIN15__IPU1_DI0_PIN15  | MUX_PAD_CTRL(0x10)),        /* DISP0 DE */
	IOMUX_PADS(PAD_DI0_PIN2__IPU1_DI0_PIN02   | MUX_PAD_CTRL(0x10)),        /* DISP0 HSync */
	IOMUX_PADS(PAD_DI0_PIN3__IPU1_DI0_PIN03   | MUX_PAD_CTRL(0x10)),        /* DISP0 VSync */
	IOMUX_PADS(PAD_DI0_PIN4__IPU1_DI0_PIN04   | MUX_PAD_CTRL(NO_PAD_CTRL)), /* DISP0 Contrast */
	
	IOMUX_PADS(PAD_DISP0_DAT0__IPU1_DISP0_DATA00 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT1__IPU1_DISP0_DATA01 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT2__IPU1_DISP0_DATA02 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT3__IPU1_DISP0_DATA03 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT4__IPU1_DISP0_DATA04 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT5__IPU1_DISP0_DATA05 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT6__IPU1_DISP0_DATA06 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT7__IPU1_DISP0_DATA07 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT8__IPU1_DISP0_DATA08 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT9__IPU1_DISP0_DATA09 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT10__IPU1_DISP0_DATA10 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT11__IPU1_DISP0_DATA11 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT12__IPU1_DISP0_DATA12 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT13__IPU1_DISP0_DATA13 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT14__IPU1_DISP0_DATA14 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT15__IPU1_DISP0_DATA15 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT16__IPU1_DISP0_DATA16 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT17__IPU1_DISP0_DATA17 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT18__IPU1_DISP0_DATA18 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT19__IPU1_DISP0_DATA19 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT20__IPU1_DISP0_DATA20 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT21__IPU1_DISP0_DATA21 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT22__IPU1_DISP0_DATA22 | MUX_PAD_CTRL(0x10)),        /* */
	IOMUX_PADS(PAD_DISP0_DAT23__IPU1_DISP0_DATA23 | MUX_PAD_CTRL(0x10)),        /* */
	
	/* uart 1 */
	IOMUX_PADS(PAD_CSI0_DAT10__UART1_TX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_CSI0_DAT11__UART1_RX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_EIM_D19__UART1_CTS_B       | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_EIM_D20__UART1_RTS_B       | MUX_PAD_CTRL(0x1b0b1)),

	/* uart 3 */
	IOMUX_PADS(PAD_EIM_D24__UART3_TX_DATA     | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_EIM_D25__UART3_RX_DATA     | MUX_PAD_CTRL(0x1b0b1)),

	/* uart 4 */
	IOMUX_PADS(PAD_CSI0_DAT12__UART4_TX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_CSI0_DAT13__UART4_RX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_CSI0_DAT17__UART4_CTS_B    | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_CSI0_DAT16__UART4_RTS_B    | MUX_PAD_CTRL(0x1b0b1)),
	
	/* uart5 */
	IOMUX_PADS(PAD_CSI0_DAT14__UART5_TX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_CSI0_DAT15__UART5_RX_DATA  | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_KEY_ROW4__UART5_CTS_B      | MUX_PAD_CTRL(0x1b0b1)),
	IOMUX_PADS(PAD_KEY_COL4__UART5_RTS_B      | MUX_PAD_CTRL(0x1b0b1)),
	
	IOMUX_PADS(PAD_EIM_CS1__GPIO2_IO24        | MUX_PAD_CTRL(NO_PAD_CTRL)), /* UART5_M1 */
	IOMUX_PADS(PAD_EIM_CS0__GPIO2_IO23        | MUX_PAD_CTRL(NO_PAD_CTRL)), /* UART5_M0 */
	IOMUX_PADS(PAD_EIM_D16__GPIO3_IO16        | MUX_PAD_CTRL(NO_PAD_CTRL)), /* UART5 enable */
	IOMUX_PADS(PAD_EIM_D17__GPIO3_IO17        | MUX_PAD_CTRL(NO_PAD_CTRL)), /* UART5 slew */
	IOMUX_PADS(PAD_EIM_BCLK__GPIO6_IO31       | MUX_PAD_CTRL(NO_PAD_CTRL)), /* UART5 TERM */
	
	/*usb otg*/
	IOMUX_PADS(PAD_ENET_RX_ER__USB_OTG_ID     | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_EIM_D22__GPIO3_IO22        | MUX_PAD_CTRL(0x000b0)),	/* USB_OTG_PWR_EN */
	IOMUX_PADS(PAD_EIM_D21__USB_OTG_OC        | MUX_PAD_CTRL(0x1b0b0)),		/* USB_OTG_OC */	

	/* usb h1*/
	IOMUX_PADS(PAD_ENET_TXD1__GPIO1_IO29      | MUX_PAD_CTRL(0x000b0)),		/* USB_H1_PWR_EN */
	IOMUX_PADS(PAD_EIM_D30__USB_H1_OC         | MUX_PAD_CTRL(0x1b0b0)),		/* USB_H1_OC */
	IOMUX_PADS(PAD_GPIO_17__GPIO7_IO12        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* USB_HUB_RESET_B */
	IOMUX_PADS(PAD_NANDF_CS2__GPIO6_IO15      | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* USB_PWR1 */
	IOMUX_PADS(PAD_NANDF_CS3__GPIO6_IO16      | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* USB_PWR2 */
	IOMUX_PADS(PAD_NANDF_D4__GPIO2_IO04       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* USB_PWR3 */	
	IOMUX_PADS(PAD_NANDF_D5__GPIO2_IO05       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* USB_PWR4 */

	/*usdhc3*/
	IOMUX_PADS(PAD_NANDF_D0__GPIO2_IO00       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* SD3_CD */
	IOMUX_PADS(PAD_NANDF_D1__GPIO2_IO01       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* SD3_WP */
	IOMUX_PADS(PAD_SD3_CMD__SD3_CMD           | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD3_CLK__SD3_CLK           | MUX_PAD_CTRL(0x10059)),
	IOMUX_PADS(PAD_SD3_DAT0__SD3_DATA0        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD3_DAT1__SD3_DATA1        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD3_DAT2__SD3_DATA2        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD3_DAT3__SD3_DATA3        | MUX_PAD_CTRL(0x17059)),
	
	/*usdhc4*/
	IOMUX_PADS(PAD_SD4_CMD__SD4_CMD           | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_CLK__SD4_CLK           | MUX_PAD_CTRL(0x10059)),
	IOMUX_PADS(PAD_SD4_DAT0__SD4_DATA0        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT1__SD4_DATA1        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT2__SD4_DATA2        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT3__SD4_DATA3        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT4__SD4_DATA4        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT5__SD4_DATA5        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT6__SD4_DATA6        | MUX_PAD_CTRL(0x17059)),
	IOMUX_PADS(PAD_SD4_DAT7__SD4_DATA7        | MUX_PAD_CTRL(0x17059)),

	/*pcie*/
	IOMUX_PADS(PAD_EIM_D18__GPIO3_IO18        | MUX_PAD_CTRL(NO_PAD_CTRL)),		/* PCIE_PWR_EN */
	IOMUX_PADS(PAD_GPIO_8__GPIO1_IO08         | MUX_PAD_CTRL(NO_PAD_CTRL)),		/* PCIE_WAKE_B */
	IOMUX_PADS(PAD_SD3_DAT4__GPIO7_IO01       | MUX_PAD_CTRL(NO_PAD_CTRL)),		/* PCIE_DIS_B */
	IOMUX_PADS(PAD_GPIO_16__GPIO7_IO11        | MUX_PAD_CTRL(NO_PAD_CTRL)),		/* PCIE_RST */	

	/*mcu*/
	IOMUX_PADS(PAD_KEY_COL0__GPIO4_IO06       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* MCU Reset */
	IOMUX_PADS(PAD_KEY_ROW0__GPIO4_IO07       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* MCU_UPDATE_PWR_ON */
	IOMUX_PADS(PAD_KEY_COL2__GPIO4_IO10       | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* MCU_BOOT_EN */

	/* key */
	IOMUX_PADS(PAD_EIM_D29__GPIO3_IO29        | MUX_PAD_CTRL(NO_PAD_CTRL)),	/* PWR_BTN_SNS */

	
};

void board_setup_pads(void)
{
	SETUP_IOMUX_PADS(iomux_v3_pads);
}
