
#ifndef __RTX_BOARD_IOMUX_H__
#define __RTX_BOARD_IOMUX_H__

#include <asm/gpio.h>

#define BOARD_PAD_LVDS_BL_ENABLE		IMX_GPIO_NR(1,17)
#define BOARD_PAD_LVDS_BL_3V3_ENABLE	IMX_GPIO_NR(1, 2)
#define BOARD_PAD_LVDS_BL_5V_ENABLE		IMX_GPIO_NR(1, 9)
#define BOARD_PAD_LVDS_BL_12V_ENABLE	IMX_GPIO_NR(2, 3)
#define BOARD_PAD_LVDS_BL_24V_ENABLE	IMX_GPIO_NR(1, 7)
#define BOARD_PAD_LVDS_MODE_SEL			IMX_GPIO_NR(3,23)

#define BOARD_PAD_LCD_EDID_ENABLE		IMX_GPIO_NR(4, 5)
#define BOARD_PAD_LCD_DAC_ENABLE		IMX_GPIO_NR(1, 4)

#define BOARD_PAD_GPIO1					IMX_GPIO_NR(1,28)
#define BOARD_PAD_GPIO2					IMX_GPIO_NR(1,27)
#define BOARD_PAD_GPIO3					IMX_GPIO_NR(1,30)
#define BOARD_PAD_GPIO4					IMX_GPIO_NR(4, 8)
#define BOARD_PAD_GPIO5					IMX_GPIO_NR(4, 9)
#define BOARD_PAD_GPIO6					IMX_GPIO_NR(3,26)
#define BOARD_PAD_GPIO7					IMX_GPIO_NR(3,27)
#define BOARD_PAD_GPIO8					IMX_GPIO_NR(3,28)
#define BOARD_PAD_GPIO9					IMX_GPIO_NR(3,31)

#define BOARD_PAD_HEADPHONE_DET			IMX_GPIO_NR(7, 8)
#define BOARD_PAD_HEADPHONE_POP_ENABLE	IMX_GPIO_NR(6, 4)
#define BOARD_PAD_AUD_AMP_STBY			IMX_GPIO_NR(2, 6)
#define BOARD_PAD_AUD_AMP_MUTE			IMX_GPIO_NR(2, 7)

#define BOARD_PAD_IR_CONTROL			IMX_GPIO_NR(7, 0)
#define BOARD_PAD_LED0_R_CONTROL		IMX_GPIO_NR(6,18)
#define BOARD_PAD_LED0_G_CONTROL		IMX_GPIO_NR(6,17)

#define BOARD_PAD_RGMII_RESET			IMX_GPIO_NR(1,25)

#define BOARD_PAD_UART5_M0				IMX_GPIO_NR(2,23)
#define BOARD_PAD_UART5_M1				IMX_GPIO_NR(2,24)
#define BOARD_PAD_UART5_ENABLE			IMX_GPIO_NR(3,16)
#define BOARD_PAD_UART5_SLEW			IMX_GPIO_NR(3,17)
#define BOARD_PAD_UART5_TERM			IMX_GPIO_NR(6,31)

#define BOARD_PAD_USB_OTG_PWR_EN		IMX_GPIO_NR(3,22)

#define BOARD_PAD_USB_H1_PWR_EN			IMX_GPIO_NR(1,29)
#define BOARD_PAD_USB_HUB_RESET			IMX_GPIO_NR(7,12)
#define BOARD_PAD_USB_P1_PWR_EN			IMX_GPIO_NR(6,15)
#define BOARD_PAD_USB_P2_PWR_EN			IMX_GPIO_NR(6,16)
#define BOARD_PAD_USB_P3_PWR_EN			IMX_GPIO_NR(2, 4)
#define BOARD_PAD_USB_P4_PWR_EN			IMX_GPIO_NR(2, 5)

#define BOARD_PAD_SD3_CD				IMX_GPIO_NR(2, 0)
#define BOARD_PAD_SD3_WP				IMX_GPIO_NR(2, 1)

#define BOARD_PAD_PCIE_PWR_EN			IMX_GPIO_NR(3,18)
#define BOARD_PAD_PCIE_WAKE				IMX_GPIO_NR(1, 8)
#define BOARD_PAD_PCIE_DISABLE			IMX_GPIO_NR(7, 1)
#define BOARD_PAD_PCIE_RESET			IMX_GPIO_NR(7,11)

#define BOARD_PAD_MCU_RESET				IMX_GPIO_NR(4, 6)
#define BOARD_PAD_MCU_PWR_KEEP			IMX_GPIO_NR(4, 7)
#define BOARD_PAD_MCU_BOOT_ENABLE		IMX_GPIO_NR(4,10)

#define BOARD_PAD_KEY_PWR_BTN			IMX_GPIO_NR(3,29)


extern void board_setup_pads(void) ;

#endif
