#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# Jason Liu <r64343@freescale.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y			+= rtx-bishop-mx53.o
obj-$(CONFIG_VIDEO)	+= rtx-bishop-mx53_video.o
