#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := board_main.o
obj-y  += board_iomux.o
obj-y  += board_spl.o
obj-y  += board_i2c.o
obj-y  += board_mmc.o
obj-y  += board_eth.o
obj-y  += board_power.o
obj-y  += board_usb.o
obj-y  += board_spi.o
obj-y  += board_display.o
