#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2009 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y			+= rtx-aeg200-mx51.o
obj-$(CONFIG_VIDEO)	+= rtx-aeg200-mx51_video.o
